# Access one of the following URLs to initiate a login flow:
#    - http://oauth2-proxy.localdev.me:5080
#    - http://httpbin.oauth2-proxy.localdev.me:5080
#
# The OAuth2 Proxy itself is hosted at http://oauth2-proxy.oauth2-proxy.localdev.me:5080
#
# Note, the above URLs should work with Chrome, but you may need to add hosts
# entries for other browsers
#    127.0.0.1 nginx.localdev.me
#    127.0.0.1 oauth2-proxy.localdev.me
#    127.0.0.1 httpbin.oauth2-proxy.localdev.me
#    127.0.0.1 oauth2-proxy.oauth2-proxy.localdev.me
version: '3.0'

version: '3.0'
services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - "./config/oauth2-proxy.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    ports: []
    networks:
      oauth2-proxy: {}
      dex: {}
    depends_on:
      - dex
      - httpbin

  dex:
    image: ghcr.io/dexidp/dex:v2.30.3
    command: dex serve /dex.yaml
    hostname: dex
    volumes:
      - "./config/dex.yaml:/dex.yaml"
    restart: unless-stopped
    ports:
      - 4190:4190/tcp
    networks:
      dex:
        aliases:
          - dex.localtest.me
      etcd: {}
    depends_on:
      - etcd

  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 8080:80/tcp
    networks:
      httpbin:
        aliases:
          - httpbin.localtest.me

  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.7
    entrypoint: /usr/local/bin/etcd
    command:
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
    networks:
      etcd: {}

  nginx:
    image: nginx:1.18
    restart: unless-stopped
    ports:
      - 5080:5080/tcp
    hostname: nginx
    volumes:
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      oauth2-proxy: {}
      httpbin: {}

networks:
  dex: {}
  etcd: {}
  httpbin: {}
  oauth2-proxy: {}